In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a teacher and I love to inspire and teach students',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of life',
    'your videos are good',
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a teacher and I love to inspire and teach students',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of life',
 'your videos are good']

In [5]:
# Define the vocabulary size:
voc_size=10000


In [ ]:
# In the output each row is representing sentence, and each element is telling the index of the word acoording to vocabulary size. 
one_hot_repr= [one_hot(words, voc_size) for words in sent]
one_hot_repr


[[5397, 3516, 4031, 4031],
 [5397, 3516, 4031, 9708],
 [5397, 8388, 4031, 6219],
 [7843, 5190, 1952, 2373, 5634, 7843, 9167, 8628, 8823, 5634, 4417, 7184],
 [7843, 5190, 1952, 2641, 4512],
 [7843, 5190, 1952, 2641, 8506],
 [9734, 5397, 835, 4031, 8378],
 [28, 4075, 384, 2641]]

In [ ]:
# word Embedding Represenation
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [ ]:
# using pad sequences to equalize the length of the sentences
sent_length = 12
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen= sent_length)


In [11]:
print(embedded_docs)

[[   0    0    0    0    0    0    0    0 5397 3516 4031 4031]
 [   0    0    0    0    0    0    0    0 5397 3516 4031 9708]
 [   0    0    0    0    0    0    0    0 5397 8388 4031 6219]
 [7843 5190 1952 2373 5634 7843 9167 8628 8823 5634 4417 7184]
 [   0    0    0    0    0    0    0 7843 5190 1952 2641 4512]
 [   0    0    0    0    0    0    0 7843 5190 1952 2641 8506]
 [   0    0    0    0    0    0    0 9734 5397  835 4031 8378]
 [   0    0    0    0    0    0    0    0   28 4075  384 2641]]


In [12]:
# Feature representation
dim = 10


In [13]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 12, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 181ms/step


array([[[-2.64902040e-03, -8.09394196e-03, -3.92181166e-02,
          2.47295164e-02,  3.40594389e-02,  3.42690386e-02,
         -2.52362490e-02,  4.24728654e-02, -4.88890298e-02,
          3.23681869e-02],
        [-2.64902040e-03, -8.09394196e-03, -3.92181166e-02,
          2.47295164e-02,  3.40594389e-02,  3.42690386e-02,
         -2.52362490e-02,  4.24728654e-02, -4.88890298e-02,
          3.23681869e-02],
        [-2.64902040e-03, -8.09394196e-03, -3.92181166e-02,
          2.47295164e-02,  3.40594389e-02,  3.42690386e-02,
         -2.52362490e-02,  4.24728654e-02, -4.88890298e-02,
          3.23681869e-02],
        [-2.64902040e-03, -8.09394196e-03, -3.92181166e-02,
          2.47295164e-02,  3.40594389e-02,  3.42690386e-02,
         -2.52362490e-02,  4.24728654e-02, -4.88890298e-02,
          3.23681869e-02],
        [-2.64902040e-03, -8.09394196e-03, -3.92181166e-02,
          2.47295164e-02,  3.40594389e-02,  3.42690386e-02,
         -2.52362490e-02,  4.24728654e-02, -4.888902